/**
 * Unified race-fetching utility.
 *
 * Priority order:
 *   1. `src/data/races-live.json`  — generated by `scripts/fetch-races.py`
 *      (runs in GitHub Actions before the Astro build)
 *   2. ProCyclingStats HTML scraping (Node.js build-time; blocked locally
 *      by Cloudflare but may work from GitHub Actions IPs)
 *   3. `src/data/seedRaces.ts`     — static fallback for local development
 *
 * After loading races from any source, stage profile images are enriched
 * via cyclingoo.com (not Cloudflare-protected, accessible at build time).
 */

import type { Race } from './procyclingstats';
import { getRecentRaces } from './procyclingstats';
import { SEED_RACES } from '../data/seedRaces';
import { enrichRacesWithCyclingoo } from './cyclingoo';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

let liveRaces: Race[] | null = null;

function loadLiveJson(): Race[] {
  if (liveRaces !== null) return liveRaces;
  try {
    // Use fs.readFileSync so a missing file fails gracefully at runtime,
    // not as a static import that Vite/Rollup would resolve at build time.
    const dir = dirname(fileURLToPath(import.meta.url));
    const jsonPath = join(dir, '../../src/data/races-live.json');
    const raw = readFileSync(jsonPath, 'utf-8');
    const data = JSON.parse(raw) as Race[];
    liveRaces = Array.isArray(data) ? data : [];
    return liveRaces;
  } catch {
    liveRaces = [];
    return [];
  }
}

export async function getAllRaces(): Promise<{ races: Race[]; source: string }> {
  let races: Race[];
  let source: string;

  // 1. Python-generated JSON (preferred)
  const live = loadLiveJson();
  if (live.length > 0) {
    races = live;
    source = 'live-json';
  } else {
    // 2. Build-time PCS scrape
    try {
      const scraped = await getRecentRaces(7);
      if (scraped.length > 0) {
        races = scraped;
        source = 'pcs-scrape';
      } else {
        throw new Error('empty');
      }
    } catch {
      // 3. Seed data
      races = SEED_RACES;
      source = 'seed';
    }
  }

  // Enrich all races with profile images from cyclingoo
  try {
    races = await enrichRacesWithCyclingoo(races);
  } catch (err) {
    console.error('[getRaces] cyclingoo enrichment failed:', err);
  }

  return { races, source };
}
