/**
 * Unified race-fetching utility.
 *
 * Priority order:
 *   1. `src/data/races-live.json`  — generated by `scripts/fetch-races.py`
 *      (runs in GitHub Actions before the Astro build)
 *   2. ProCyclingStats HTML scraping (Node.js build-time; blocked locally
 *      by Cloudflare but may work from GitHub Actions IPs)
 *   3. `src/data/seedRaces.ts`     — static fallback for local development
 *
 * After loading races, stage profile images are enriched in two passes:
 *   1. Supabase `stage_profiles` table (one DB query, no external fetches)
 *   2. cyclingoo.com fallback for any stages still missing an image
 */

import type { Race, Stage } from './procyclingstats';
import { getRecentRaces } from './procyclingstats';
import { SEED_RACES } from '../data/seedRaces';
import { enrichRacesWithCyclingoo } from './cyclingoo';
import { getStageProfilesByYear, type StageProfile } from './supabase';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

let liveRaces: Race[] | null = null;

function loadLiveJson(): Race[] {
  if (liveRaces !== null) return liveRaces;
  try {
    // Use fs.readFileSync so a missing file fails gracefully at runtime,
    // not as a static import that Vite/Rollup would resolve at build time.
    const dir = dirname(fileURLToPath(import.meta.url));
    const jsonPath = join(dir, '../../src/data/races-live.json');
    const raw = readFileSync(jsonPath, 'utf-8');
    const data = JSON.parse(raw) as Race[];
    liveRaces = Array.isArray(data) ? data : [];
    return liveRaces;
  } catch {
    liveRaces = [];
    return [];
  }
}

export async function getAllRaces(): Promise<{ races: Race[]; source: string }> {
  let races: Race[];
  let source: string;

  // 1. Python-generated JSON (preferred)
  const live = loadLiveJson();
  if (live.length > 0) {
    races = live;
    source = 'live-json';
  } else {
    // 2. Build-time PCS scrape
    try {
      const scraped = await getRecentRaces(7);
      if (scraped.length > 0) {
        races = scraped;
        source = 'pcs-scrape';
      } else {
        throw new Error('empty');
      }
    } catch {
      // 3. Seed data
      races = SEED_RACES;
      source = 'seed';
    }
  }

  // Enrich stages with profile images from Supabase (one DB query, no external fetches)
  try {
    races = await enrichRacesWithSupabase(races);
  } catch (err) {
    console.error('[getRaces] supabase enrichment failed:', err);
  }

  // Fall back to cyclingoo for any stages still missing a profile image
  try {
    races = await enrichRacesWithCyclingoo(races);
  } catch (err) {
    console.error('[getRaces] cyclingoo enrichment failed:', err);
  }

  // Filter races and stages to only include content that has already started.
  // For stage races, individual stages in the future are removed.
  const today = new Date();
  today.setHours(23, 59, 59, 999);

  races = races
    // Drop races that haven't started yet
    .filter((r) => {
      const start = r.startDate ? new Date(r.startDate + 'T00:00:00Z') : null;
      return start !== null && start <= today;
    })
    // Drop individual future stages (e.g. stage 8 of an ongoing race)
    .map((r) => ({
      ...r,
      stages: r.stages.filter((s) => {
        if (!s.date) return true; // no date info → keep (one-day race with single stage)
        return new Date(s.date + 'T23:59:59Z') <= today;
      }),
    }))
    // Drop races left with no stages after filtering
    .filter((r) => r.stages.length > 0);

  return { races, source };
}

// ─── Supabase enrichment ─────────────────────────────────────────────────────

/**
 * Enrich races with profile images stored in the `stage_profiles` Supabase table.
 * Matches on `stage_pcs_url` (exact URL match, trailing slash normalised).
 * Also fills in `distanceKm` when not already set.
 * Stages already having a `profileImageUrl` are left unchanged.
 */
async function enrichRacesWithSupabase(races: Race[]): Promise<Race[]> {
  const year = new Date().getFullYear();
  const profiles = await getStageProfilesByYear(year);
  if (profiles.length === 0) {
    console.log('[getRaces] no stage_profiles found in Supabase for', year);
    return races;
  }
  console.log(`[getRaces] supabase: ${profiles.length} stage profiles loaded`);

  // Build a lookup by normalised stage_pcs_url
  const byUrl = new Map<string, StageProfile>();
  for (const p of profiles) {
    if (p.stage_pcs_url) {
      byUrl.set(p.stage_pcs_url.replace(/\/$/, ''), p);
    }
  }

  return races.map((race) => ({
    ...race,
    stages: race.stages.map((stage): Stage => {
      const url = stage.url.replace(/\/$/, '');
      const p = byUrl.get(url);
      if (!p) return stage;
      return {
        ...stage,
        profileImageUrl: stage.profileImageUrl ?? p.profile_image_url,
        distanceKm: stage.distanceKm ?? (p.distance_km != null ? Number(p.distance_km) : null),
      };
    }),
  }));
}
