/**
 * Unified race-fetching utility.
 *
 * Priority order:
 *   1. `src/data/races-live.json`  — generated by `scripts/fetch-races.py`
 *      (runs in GitHub Actions before the Astro build)
 *   2. ProCyclingStats HTML scraping (Node.js build-time; blocked locally
 *      by Cloudflare but may work from GitHub Actions IPs)
 *   3. `src/data/seedRaces.ts`     — static fallback for local development
 */

import type { Race } from './procyclingstats';
import { getRecentRaces } from './procyclingstats';
import { SEED_RACES } from '../data/seedRaces';
import { readFileSync } from 'node:fs';
import { fileURLToPath } from 'node:url';
import { join, dirname } from 'node:path';

let liveRaces: Race[] | null = null;

function loadLiveJson(): Race[] {
  if (liveRaces !== null) return liveRaces;
  try {
    // Use fs.readFileSync so a missing file fails gracefully at runtime,
    // not as a static import that Vite/Rollup would resolve at build time.
    const dir = dirname(fileURLToPath(import.meta.url));
    const jsonPath = join(dir, '../../src/data/races-live.json');
    const raw = readFileSync(jsonPath, 'utf-8');
    const data = JSON.parse(raw) as Race[];
    liveRaces = Array.isArray(data) ? data : [];
    return liveRaces;
  } catch {
    liveRaces = [];
    return [];
  }
}

export async function getAllRaces(): Promise<{ races: Race[]; source: string }> {
  // 1. Python-generated JSON (preferred)
  const live = loadLiveJson();
  if (live.length > 0) {
    return { races: live, source: 'live-json' };
  }

  // 2. Build-time PCS scrape
  try {
    const scraped = await getRecentRaces(7);
    if (scraped.length > 0) {
      return { races: scraped, source: 'pcs-scrape' };
    }
  } catch {
    // fall through
  }

  // 3. Seed data
  return { races: SEED_RACES, source: 'seed' };
}
